# 设置RISC-V特定的链接器选项
set(CMAKE_EXE_LINKER_FLAGS "-nostartfiles -static -Wl,--gc-sections -Wl,-static")
set(CMAKE_SHARED_LINKER_FLAGS "-nostartfiles -static")

# 设置输出格式为ELF
set(CMAKE_EXECUTABLE_SUFFIX ".elf")

# 禁用Windows PE格式相关的链接器选项
set(CMAKE_EXE_LINKER_FLAGS_INIT "")
set(CMAKE_MODULE_LINKER_FLAGS_INIT "")
set(CMAKE_SHARED_LINKER_FLAGS_INIT "")
set(CMAKE_STATIC_LINKER_FLAGS_INIT "")

# 强制使用RISC-V的链接器选项
set_property(GLOBAL PROPERTY TARGET_SUPPORTS_SHARED_LIBS FALSE)
set(CMAKE_FIND_LIBRARY_PREFIXES "lib")
set(CMAKE_FIND_LIBRARY_SUFFIXES ".a")
set(CMAKE_C_IMPLICIT_LINK_LIBRARIES "")
set(CMAKE_CXX_IMPLICIT_LINK_LIBRARIES "") 